<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\besti2.Domain\besti2.Domain.csproj" />
      <ProjectReference Include="..\besti2.Application\besti2.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.12" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
    </ItemGroup>

</Project>
